### ISSUE TITLE
python3.5: AttributeError: 'itertools.cycle' object has no attribute 'next'

### ISSUE THREAD

**Issue by msimonin** [msimonin/ombt-orchestrator#103]
When launching a campaign using python 3.5 I hit this: 

```
Traceback (most recent call last):
  File "./cli.py", line 301, in <module>
    cli()
  File "/Users/msimonin/.pyenv/versions/ombt-orchestrator-3.5.2/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/msimonin/.pyenv/versions/ombt-orchestrator-3.5.2/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/msimonin/.pyenv/versions/ombt-orchestrator-3.5.2/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/msimonin/.pyenv/versions/ombt-orchestrator-3.5.2/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/msimonin/.pyenv/versions/ombt-orchestrator-3.5.2/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./cli.py", line 291, in campaign
    env=env)
  File "/Users/msimonin/msimonin@github.com/ombt-orchestrator/campaign.py", line 296, in incremental_campaign
    group_id = groups.next()
AttributeError: 'itertools.cycle' object has no attribute 'next'```

This seeems related to python3

**Comment by jrbalderrama** [comment]
my bad `next` was removed from python 3. we shoud use `next(iterator)` instead. It also applies to variable `iterations`
