### ISSUE TITLE
add AttributeError to list of managed exceptions during campaign

### ISSUE THREAD

**Issue by jrbalderrama** [msimonin/ombt-orchestrator#91]
```
Traceback (most recent call last):
  File "./cli.py", line 301, in <module>
    cli()
  File "/home/jarojasbalderrama/.pyenv/versions/ombt-2.7.14/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jarojasbalderrama/.pyenv/versions/ombt-2.7.14/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jarojasbalderrama/.pyenv/versions/ombt-2.7.14/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jarojasbalderrama/.pyenv/versions/ombt-2.7.14/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jarojasbalderrama/.pyenv/versions/ombt-2.7.14/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./cli.py", line 291, in campaign
    env=env)
  File "/home/jarojasbalderrama/workspace/ombt-orchestrator/campaign.py", line 285, in incremental_campaign
    t.prepare(driver=current_driver, env=env_dir)
  File "/home/jarojasbalderrama/.pyenv/versions/ombt-2.7.14/lib/python2.7/site-packages/enoslib/task.py", line 50, in decorated
    fn(*args, **kwargs)
  File "/home/jarojasbalderrama/workspace/ombt-orchestrator/tasks.py", line 357, in prepare
    ansible_bus_conf = generate_ansible_conf(config, 'bus')
  File "/home/jarojasbalderrama/workspace/ombt-orchestrator/tasks.py", line 348, in generate_ansible_conf
    bus_conf = generate_bus_conf(configuration, machines)
  File "/home/jarojasbalderrama/workspace/ombt-orchestrator/tasks.py", line 325, in generate_bus_conf
    bus_conf = get_conf(graph, machines, round_robin)
  File "/home/jarojasbalderrama/workspace/ombt-orchestrator/qpid_dispatchgen.py", line 14, in get_conf
    for node, nbrdict in graph.adjacency_iter():
AttributeError: 'Graph' object has no attribute 'adjacency_iter'
```

**Comment by jrbalderrama** [comment]
@msimonin do you know it that is related to any unattended behaviour of the dispatch generator?
